
import "./globals.css";
import  Providers  from "./providers";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="" lang="en"> {/*todo:Add change theme func*/}
      <Providers>
        <body className="">{children}</body>
      </Providers>
    </html>
  );
}
